### ISSUE TITLE
Autocorrelation curve shifted

### ISSUE THREAD

**Issue by tneg** [tritemio/pycorrelate#4]
* Pycorrelate version: 0.3
* Python version: 3.6.5
* Operating System: Ubuntu 18.04

### Description

When calculating the autocorrelation curve for a FCS experiment with pycorrelate the curve has the right shape but seems to be shifted to smaller lag times. Am I doing something fundamentally wrong when using pycorrelate?

### What I Did
The original .pt3 file and the extracted arrival times (in seconds):
[data.zip](https://github.com/tritemio/pycorrelate/files/2213562/data.zip)

My code to generate the autocorrelation curves
`import pycorrelate as pyc
import numpy as np
import matplotlib.pyplot as plt
file = 'Point_5_extracted'
with open(file) as f:
    new = f.readlines()
nparray = np.array(new)
times = nparray.astype(np.float)
times = np.sort(times)
lags = pyc.make_loglags(-7,-2,20)

G = pyc.pcorrelate(times,times,lags,normalize=True)

plt.semilogx(lags[:-1],G-1)
plt.show()`

The autocorrelation curve generated with PyCorrFit:
![pycorrfit](https://user-images.githubusercontent.com/41374909/42998760-31ba371c-8c13-11e8-9572-42b82382bc82.png)

The autocorrelation curve generated with pycorrelate:
![pycorrelate](https://user-images.githubusercontent.com/41374909/42998766-396e9232-8c13-11e8-8a4c-5e506f2e38ac.png)

**Comment by tritemio** [comment]
To avoid floating point issues, I suggest to leave the `times` as integers (`np.int64`) in raw hardware units and express the lag-bins in these raw units. For example:

```
lags = pyc.make_loglags(1,7,20).astype('int64')
```

 Then, for plotting, you can rescale the time lags to seconds.

**Comment by tneg** [comment]
Thanks a lot for the fast answer! I think my problems were caused by floating point issues

**Comment by tritemio** [comment]
Your a welcome!

In the future, please open an issue under the OpenSMFS page: https://github.com/OpenSMFS/pycorrelate/issues.
