### ISSUE TITLE
ucorrelate with floats

### ISSUE THREAD

**Issue by berna1111** [tritemio/pycorrelate#5]
* Pycorrelate version: 0.3
* Python version: 3.6.6
* Operating System: windows 10

### Description

Calculating correlation of arrays with floats.

### What I Did
Changing line 159 in pycorrelate.py from:
`    C = np.zeros(maxlag, dtype=np.int64)`
to:
`    C = np.empty(maxlag, dtype=t.dtype)`
Fixes the issue.

The important change is from `np.int64` to `t.dtype`.

Changing `zeros` to `empty` only speeds up the function a little, as it avoids filling C with zeros before filling it with the correct values, and can also be applied to lines 79, 82 and 84. As a rule of thumb, as long as the array will have all of it's positions filled right after it's creation, calling np.empty is marginally faster than calling np.zeros.

Before the change:
```
    import numpy as np
    import pycorrelate
    t = np.array([1.2, 2.4, 0.5, 0.6])
    u = np.array([0, 1.2, 1.3])
    pycorrelate.ucorrelate(t, u)
    # array([3, 4, 1], dtype=int64)
```

After the change the same input produces:
```
    # array([3.53, 4.56, 1.56])
```

**Comment by tritemio** [comment]
Hi @berna1111,

thanks for the report and the fix! Would you mind sending a PR with the fix to the new pycorrelate address under the OpenSMFS organization?

https://github.com/opensmfs/pycorrelate

This will make sure your contribution is recorded and acknowledged.

Thanks.

**Comment by berna1111** [comment]
Sorry for the delay, had to get home before doing this correctly.

I believe there should now be a pull request on OpenSMFS.

Thank you for making this library available in the first place.

**Comment by tritemio** [comment]
There isn't. If you are not familiar with the process, you first need to fork the OpenSMFS/pycorrelate repository, do the modifications on your fork and then send a Pull Request from your fork to OpenSMFS/pycorrelate using the github web interface.

**Comment by berna1111** [comment]
Yes, this was my first Pull Request - I now understand I tried to work on the main project, for which I [rightfully] have no writing privileges, and missed the warning that the file could not be changed. So after a few attempts I can now see the pull request from my fork. Sorry for the mess up, best regards.
(also, I don't know the formalities/process, but I guess this issue can be closed?)

**Comment by tritemio** [comment]
Yes, thanks for going through the hops to make a PR!

**Comment by tritemio** [comment]
xref: https://github.com/OpenSMFS/pycorrelate/pull/1
