### ISSUE TITLE
runtime performance of ucorrelate is disappointing

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [tritemio/pycorrelate#7]
* Pycorrelate version: 0.3
* Python version: 3.6
* Operating System: Windows 10

### Description

I wrote a script to compare the runtime perforance of `numpy.correlate` and `pycorrelate.ucorrelate`.  The input sequences have length 1e5, and the maximum lag of interest is 10,000.  Since I can't specify a maximum lag with `numpy.correlate`, I used the `mode='same'` option.

Although `numpy.correlate` does the full cross-correlation, and was thus expected to be much slower, the results showed that it is actually faster (the following test results are based on 10 iterations in each case):

  elapsed (wall time)   | user CPU | system CPU

          numpy:  37.03 | 141.09   |   6.92
    pycorrelate: 106.91 |  55.62   |  51.78

I'm wondering if you have any thoughts re. why the elapse time is worse for `pycorrelate.ucorrelate`.  Also, have you considering using FFTs to speed up the calculations?

**Comment by tritemio** [comment]
Issue moved to https://github.com/OpenSMFS/pycorrelate/issues/4.
